### ISSUE TITLE
1.4.1 breaks old node

### ISSUE THREAD

**Issue by raylu** [evcohen/jsx-ast-utils#31]
(1.4.1 is just #30)

On node v0.10.33 (the version in Ubuntu trusty/14.04), 1.4.0 works but 1.4.1 gives
```
> require('jsx-ast-utils')
TypeError: undefined is not a function
    at Object.<anonymous> (/tmp/node_modules/jsx-ast-utils/lib/values/expressions/index.js:106:28)
```

This gets surfaced by eslint-plugin-react as
```
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, [...some misleading stuff]
```

**Comment by ljharb** [comment]
That line points to https://npmcdn.com/jsx-ast-utils@1.4.1/lib/values/expressions/index.js → https://github.com/evcohen/jsx-ast-utils/blob/master/src/values/expressions/index.js#L44 - this can be fixed by @raylu by polyfilling it, but it can and should be fixed here by importing a standalone function for it.

Luckily, https://npmjs.com/object.assign works for both cases ;-)

**Comment by ljharb** [comment]
We should probably run tests on 0.10 if possible, to avoid similar regressions.

**Comment by evcohen** [comment]
Still crazy to me that 1.4.0 works, though???

**Comment by ljharb** [comment]
Using babel often gives you es3 for free ¯\_(ツ)_/¯

**Comment by ljharb** [comment]
@evcohen this may be causing a breaking change in eslint-plugin-react; see https://github.com/yannickcr/eslint-plugin-react/issues/1158.

**Comment by evcohen** [comment]
fack i still don't get how this broke, the code didnt change

**Comment by raylu-stripe** [comment]
Sorry, I misdiagnosed what was in 1.4.1. It wasn't just PR 30.

It broke with https://github.com/evcohen/jsx-ast-utils/commit/93fdce184b3b8778c424986ca54d0284ec02f6ef and #25, but based on the referenced PR you already figured it out.

**Comment by raylu** [comment]
Sorry, I misdiagnosed what was in 1.4.1. It wasn't just PR 30.

It broke with 93fdce1 and #25, but based on the referenced PR you already figured it out.
